'use client';

import {useState, FormEvent} from 'react';
import {useRouter} from 'next/navigation';
import {VideoUploader} from '@/components/video/VideoUploader';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {ArrowLeftIcon, HardDriveUploadIcon, LinkIcon} from 'lucide-react';
import {UploadResult} from '@/hooks/useVideoUpload';
import {cn} from '@/lib/utils';

type Tab = 'disk' | 'link';

function extractClaimToken(input: string): string | null {
  const trimmed = input.trim();
  const urlMatch = trimmed.match(/\/claim\/([A-Za-z0-9_\-]+)$/);
  if (urlMatch) return urlMatch[1];
  if (/^[A-Za-z0-9_\-]{10,}$/.test(trimmed)) return trimmed;
  return null;
}

export default function UploadPage() {
  const [uploadComplete, setUploadComplete] = useState(false);
  const [uploadResult, setUploadResult] = useState<UploadResult | null>(null);
  const [tab, setTab] = useState<Tab>('disk');
  const [claimLink, setClaimLink] = useState('');
  const [claimError, setClaimError] = useState<string | null>(null);
  const router = useRouter();

  const handleUploadComplete = (result: UploadResult) => {
    setUploadResult(result);
    setUploadComplete(true);
  };

  const handleClaimSubmit = (e: FormEvent) => {
    e.preventDefault();
    setClaimError(null);
    const token = extractClaimToken(claimLink);
    if (!token) {
      setClaimError('Paste a valid claim link (e.g. https://viewer.saivd.io/claim/…) or just the token.');
      return;
    }
    router.push(`/claim/${token}`);
  };

  return (
    <div className="container mx-auto py-8 max-w-3xl">
      <div className="flex items-center mb-6">
        <Button variant="ghost" size="icon" onClick={() => router.back()}>
          <ArrowLeftIcon className="h-5 w-5" />
        </Button>
        <h1 className="text-2xl font-bold ml-2">Upload Video</h1>
      </div>

      {!uploadComplete ? (
        <div className="bg-white dark:bg-gray-800 rounded-lg shadow p-6">
          {/* Tab switcher */}
          <div className="flex gap-2 mb-6">
            <button
              onClick={() => setTab('disk')}
              className={cn(
                'flex items-center gap-2 px-4 py-2 rounded-md text-sm font-medium border transition-colors',
                tab === 'disk'
                  ? 'bg-gray-900 text-white border-gray-900 dark:bg-gray-100 dark:text-gray-900 dark:border-gray-100'
                  : 'text-gray-600 border-gray-200 hover:bg-gray-50 dark:text-gray-300 dark:border-gray-700 dark:hover:bg-gray-700'
              )}>
              <HardDriveUploadIcon className="h-4 w-4" />
              Upload from disk
            </button>
            <button
              onClick={() => setTab('link')}
              className={cn(
                'flex items-center gap-2 px-4 py-2 rounded-md text-sm font-medium border transition-colors',
                tab === 'link'
                  ? 'bg-gray-900 text-white border-gray-900 dark:bg-gray-100 dark:text-gray-900 dark:border-gray-100'
                  : 'text-gray-600 border-gray-200 hover:bg-gray-50 dark:text-gray-300 dark:border-gray-700 dark:hover:bg-gray-700'
              )}>
              <LinkIcon className="h-4 w-4" />
              Claim from link
            </button>
          </div>

          {tab === 'disk' && (
            <>
              <p className="text-gray-500 dark:text-gray-400 mb-6">
                Supported formats: MP4, MOV, AVI, WEBM. Maximum file size: 500MB.
              </p>
              <VideoUploader onUploadComplete={handleUploadComplete} />
            </>
          )}

          {tab === 'link' && (
            <form onSubmit={handleClaimSubmit} className="space-y-4">
              <p className="text-gray-500 dark:text-gray-400">
                Paste a claim link generated by a SAIVD creator to add their watermarked video to your library.
              </p>
              <Input
                value={claimLink}
                onChange={e => {
                  setClaimLink(e.target.value);
                  setClaimError(null);
                }}
                placeholder="https://viewer.saivd.io/claim/…"
                className="font-mono text-sm"
                autoFocus
              />
              {claimError && (
                <p className="text-sm text-red-500">{claimError}</p>
              )}
              <Button type="submit" disabled={!claimLink.trim()} className="w-full">
                <LinkIcon className="mr-2 h-4 w-4" />
                Open claim page
              </Button>
            </form>
          )}
        </div>
      ) : (
        <div className="bg-white dark:bg-gray-800 rounded-lg shadow p-6 text-center">
          <div className="mb-6">
            <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-green-100 dark:bg-green-900/20 mb-4">
              <svg className="w-8 h-8 text-green-600 dark:text-green-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
              </svg>
            </div>
            <h2 className="text-2xl font-semibold text-green-600 dark:text-green-400 mb-2">
              Upload Complete!
            </h2>
            <p className="text-gray-600 dark:text-gray-400 mb-4">
              Your video has been uploaded successfully and is now available in your video library.
            </p>
            {uploadResult && (
              <div className="mt-4 p-4 bg-gray-50 dark:bg-gray-700 rounded-lg text-left max-w-md mx-auto">
                <h3 className="font-medium mb-2 text-gray-900 dark:text-gray-100">Video Details</h3>
                <p className="text-sm text-gray-700 dark:text-gray-300">
                  <span className="font-medium">Filename:</span> {uploadResult.filename}
                </p>
              </div>
            )}
          </div>
          <div className="flex justify-center gap-3">
            <Button variant="outline" onClick={() => { setUploadComplete(false); setUploadResult(null); }}>
              Upload Another Video
            </Button>
            <Button onClick={() => router.push('/dashboard/videos')}>
              View My Videos
            </Button>
          </div>
        </div>
      )}
    </div>
  );
}
